# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assassin_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=34.140808),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=-118.412303),
        ),
    ]
